version: 0.2


phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn clean package

  post_build:
    commands:
      - echo Build completed sucessfully

artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes


